engines:
  duplication:
    enabled: true
    exclude_paths:
      - little_brother/test/**
      - little_brother/alembic/versions/**

exclude_paths:
  - 'little_brother/templates/**'
  - 'little_brother/static/contrib/**'